version: 2
jobs:
  step-1-1:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - run: 
          shell: /usr/bin/env ruby
          command: a = 1
  step-1-2:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - run: 
          command: sleep 120s

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - step-1-1
      - step-1-2
