version: 2
jobs:
  step-1-1:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Step 1.1"
  step-1-2:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Step 1.2"
  step-1-3:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Step 1.3"
  step-2-1:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Step 2.1"
  step-2-2:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Step 2.2"
  step-2-3:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Step 2.3"
  final-step:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Final step"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - step-1-1
      - step-1-2
      - step-1-3
      - step-2-1:
          requires:
            - step-1-1
            - step-1-2
            - step-1-3
      - step-2-2:
          requires:
            - step-1-1
            - step-1-2
            - step-1-3
      - step-2-3:
          requires:
            - step-1-1
            - step-1-2
            - step-1-3
      - final-step:
          requires:
            - step-2-1
            - step-2-2
            - step-2-3
