version: 2
jobs:
  step-1-1:
    docker:
      - image: appfolio/property_test_base:0.0.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: appfolio/property_test_base:0.0.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        entrypoint: ['dockerize', '-wait', 'tcp://127.0.0.1:3306', '-timeout', '1m']
      - image: circleci/mysql:5.6
    steps:
      - run: echo "Step 1.1"
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run: sleep 10
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - step-1-1
