version: 2
jobs:
  messenger_integration_test:
    docker:
    - image: appfolio/property_test_base:0.0.10
      auth:
        username: "$DOCKERHUB_USER"
        password: "$DOCKERHUB_PASSWORD"
    working_directory: /root/repo
    steps:
    - run: echo "Something"
    - run: circleci-agent halt
    - run: echo "Something else"
          

workflows:
  version: 2
  messenger_integration_test:
    jobs:
      - messenger_integration_test
