version: 2
jobs:
  step-1-1:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: echo "Step 1.1"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - step-1-1
